import { Achievement, DailyMission, RoutineTask, StyleItem } from '../types';

export const initialDailyMissions: DailyMission[] = [
  {
    id: 'm1',
    title: 'Hydrate & Morning Barrier',
    description: 'Cleanse face and apply moisturizer + SPF 50 sunscreen.',
    xp: 25,
    completed: false,
    category: 'skincare',
  },
  {
    id: 'm2',
    title: 'Precision Neck Lineup',
    description: 'Check neck hair border 1cm above Adam’s apple and tidy edges.',
    xp: 30,
    completed: false,
    category: 'grooming',
  },
  {
    id: 'm3',
    title: 'Take A Properly Lit Selfie',
    description: 'Capture a progress photo facing soft natural daylight at eye level.',
    xp: 50,
    completed: false,
    category: 'photo',
  },
];

export const initialAchievements: Achievement[] = [
  {
    id: 'ach_1',
    title: 'First Scan Completed',
    description: 'Began your aesthetic evolution journey with your first scan.',
    icon: '⚡',
    unlocked: true,
    progress: 1,
    max: 1,
  },
  {
    id: 'ach_2',
    title: 'Routine Master',
    description: 'Complete all morning and evening habits for 3 consecutive days.',
    icon: '🔥',
    unlocked: false,
    progress: 1,
    max: 3,
  },
  {
    id: 'ach_3',
    title: 'Style Explorer',
    description: 'Bookmark at least 3 hairstyles or frames in the Style Lab.',
    icon: '✂️',
    unlocked: false,
    progress: 0,
    max: 3,
  },
  {
    id: 'ach_4',
    title: 'Evolution Chronicler',
    description: 'Log 3 progress photos over time to activate evolution tracking.',
    icon: '📈',
    unlocked: false,
    progress: 1,
    max: 3,
  },
  {
    id: 'ach_5',
    title: 'Master Groomer',
    description: 'Reach Level 5 through consistent daily check-ins and mission completion.',
    icon: '👑',
    unlocked: false,
    progress: 1,
    max: 5,
  },
];

export const initialRoutineTasks: RoutineTask[] = [
  {
    id: 'r_m1',
    title: 'Gentle Low-pH Foam Wash',
    subtitle: 'Rinse with cool water, pat dry with fresh towel',
    timeOfDay: 'morning',
    completed: true,
    category: 'skincare',
  },
  {
    id: 'r_m2',
    title: 'Hydrating Gel & Broad SPF 50',
    subtitle: 'Protects skin barrier and prevents sun-induced photo aging',
    timeOfDay: 'morning',
    completed: false,
    category: 'skincare',
  },
  {
    id: 'r_m3',
    title: 'Hair & Brow Check',
    subtitle: 'Apply light texture clay and brush eyebrows upward',
    timeOfDay: 'morning',
    completed: false,
    category: 'grooming',
  },
  {
    id: 'r_e1',
    title: 'Evening Deep Cleanse',
    subtitle: 'Wash off daily pollutants and sunscreen residues',
    timeOfDay: 'evening',
    completed: false,
    category: 'skincare',
  },
  {
    id: 'r_e2',
    title: 'Barrier Restoration Cream',
    subtitle: 'Nourish with ceramides and apply nourishing lip balm',
    timeOfDay: 'evening',
    completed: false,
    category: 'skincare',
  },
  {
    id: 'r_e3',
    title: 'Posture & Jaw Relaxation',
    subtitle: '5 minutes tongue resting posture (mewing) & neck stretch',
    timeOfDay: 'evening',
    completed: false,
    category: 'hygiene',
  },
];

export const initialStyleItems: StyleItem[] = [
  // Haircuts
  {
    id: 'sh_1',
    category: 'hair',
    name: 'Textured French Crop with Low Taper',
    compatibilityTag: 'Oval, Square, Round',
    whyItWorks: 'The forward fringe shortens perceived forehead height while high taper temples accentuate mandibular definition.',
    maintenance: 'Medium',
    howToTry: 'Tell your barber: Leave 2 inches on top with blunt textured shear cut, low taper on sideburns and neckline.',
    tags: ['Short', 'Modern', 'Textured'],
  },
  {
    id: 'sh_2',
    category: 'hair',
    name: 'Modern Textured Quiff with Matte Finish',
    compatibilityTag: 'Oval, Diamond, Oblong',
    whyItWorks: 'Elevated vertical crown adds confident height while side taper maintains clean cranial width balance.',
    maintenance: 'High',
    howToTry: 'Ask for scissor-cut length on top (3-4 inches), blow dry upward with round brush, finish with matte clay.',
    tags: ['Medium', 'Voluminous', 'Classic'],
  },
  {
    id: 'sh_3',
    category: 'hair',
    name: 'Relaxed Mid-Length Curtain Flow',
    compatibilityTag: 'Heart, Oval, Diamond',
    whyItWorks: 'Soft lateral curtain drape conceals wide temple transitions and flatters natural jaw taper.',
    maintenance: 'Low',
    howToTry: 'Grow hair to 5-6 inches. Ask stylist for soft layers to encourage natural parting without heavy bulk.',
    tags: ['Medium', 'Flow', 'Modern'],
  },
  {
    id: 'sh_4',
    category: 'hair',
    name: 'Classic Ivy League / Side Part',
    compatibilityTag: 'Square, Oval, Oblong',
    whyItWorks: 'Time-tested architectural discipline that compliments clean jawline angles and professional styling.',
    maintenance: 'Medium',
    howToTry: 'Ask for a #3 on sides tapering down, scissors trim on top with clean side parting line.',
    tags: ['Short', 'Classic', 'Clean'],
  },
  // Beard
  {
    id: 'sb_1',
    category: 'beard',
    name: '3-Day Designer Stubble (3mm)',
    compatibilityTag: 'Universal · High Definition',
    whyItWorks: 'Darkens the lower jawline outline, casting an illusion of sharp gonial angle transition.',
    maintenance: 'Low',
    howToTry: 'Trim every 48 hours using 3mm guard. Shave all neck hair below 1cm over Adam’s apple.',
    tags: ['Stubble', 'Rugged', 'Sharp'],
  },
  {
    id: 'sb_2',
    category: 'beard',
    name: 'Short Boxed Beard (4-5mm)',
    compatibilityTag: 'Heart, Round, Oblong',
    whyItWorks: 'Adds structured horizontal substance to narrower chins, balancing midface width.',
    maintenance: 'Medium',
    howToTry: 'Maintain clean cheek line and crisp neckline with sharp corner angles.',
    tags: ['Full', 'Architectural'],
  },
  {
    id: 'sb_3',
    category: 'beard',
    name: 'Clean Shave with Hydrated Finish',
    compatibilityTag: 'Strong Mandibular Bone Structure',
    whyItWorks: 'Directly displays prominent facial bone symmetry without distracting facial hair coverage.',
    maintenance: 'High',
    howToTry: 'Shave after hot shower with single blade razor and follow with alcohol-free soothing balm.',
    tags: ['Clean', 'Minimal'],
  },
  // Glasses
  {
    id: 'sg_1',
    category: 'glasses',
    name: 'Matte Square Geometric Acetate',
    compatibilityTag: 'Round, Oval Faces',
    whyItWorks: 'Sharp 90-degree corners counterbalance soft cheek contours and define eye sockets.',
    maintenance: 'Low',
    howToTry: 'Choose 49-51mm lens width in matte black or deep charcoal tortoise.',
    tags: ['Geometric', 'Bold'],
  },
  {
    id: 'sg_2',
    category: 'glasses',
    name: 'Rounded P3 Titanium Wire Frames',
    compatibilityTag: 'Square, Angular Faces',
    whyItWorks: 'Circular curves soften strong chiselled jawline angles and avoid visual heaviness.',
    maintenance: 'Low',
    howToTry: 'Opt for brushed silver or gunmetal titanium with flexible silicone bridge pads.',
    tags: ['Minimal', 'Lightweight'],
  },
  {
    id: 'sg_3',
    category: 'glasses',
    name: 'Classic Clubmaster / Browline',
    compatibilityTag: 'Oval, Diamond, Pear',
    whyItWorks: 'Heavy upper browline frame anchors forehead width and mirrors natural eyebrow angle.',
    maintenance: 'Medium',
    howToTry: 'Match frame width precisely to your zygomatic cheekbone width.',
    tags: ['Classic', 'Vintage'],
  },
  // Style
  {
    id: 'ss_1',
    category: 'style',
    name: 'Minimalist Monochrome Capsule',
    compatibilityTag: 'All Body Types',
    whyItWorks: 'Unbroken vertical color continuity (charcoal, navy, black) elongates silhouette and projects quiet confidence.',
    maintenance: 'Low',
    howToTry: 'Pair tailored dark trousers with premium heavyweight crewneck knit and clean minimalist sneakers.',
    tags: ['Minimal', 'Versatile'],
  },
  {
    id: 'ss_2',
    category: 'style',
    name: 'Architectural Smart Casual',
    compatibilityTag: 'Athletic, Lean Frames',
    whyItWorks: 'Structured collar and shoulder seam placement frame the head and upper neck posture.',
    maintenance: 'Medium',
    howToTry: 'Wear a structured wool overshirt over crisp white tee with straight-leg selvedge denim.',
    tags: ['Smart Casual', 'Layered'],
  },
  {
    id: 'ss_3',
    category: 'style',
    name: 'Modern Elevated Streetwear',
    compatibilityTag: 'Contemporary & Youthful',
    whyItWorks: 'Relaxed proportions balance facial features and exude effortless presence.',
    maintenance: 'Low',
    howToTry: 'Drop-shoulder textured tee, wide pleated chinos, clean retro court shoes.',
    tags: ['Streetwear', 'Casual'],
  },
];
